version: "3.8"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    